# ==============================================================================
# CTFlows Coverage Post-Processing
# ==============================================================================
#
# This script post-processes coverage data generated by Julia's code coverage
# system to produce human-readable reports and CI-compatible artifacts.
#
# Prerequisites:
# - The Coverage package must be installed in your base Julia environment:
#   julia --project=@v1.12 -e 'using Pkg; Pkg.add("Coverage")'
#
# Usage:
#   julia --project=@. -e 'using Pkg; Pkg.test("CTFlows"; coverage=true); include("test/coverage.jl")'
#
# Artifacts generated:
# - coverage/lcov.info: LCOV format for CI integration (e.g., Codecov)
# - coverage/cov_report.md: Human-readable summary with uncovered lines
# - coverage/cov/: Archived .cov files
#
# ==============================================================================

pushfirst!(LOAD_PATH, @__DIR__)
using Coverage
using CTBase
CTBase.postprocess_coverage(; root_dir=dirname(@__DIR__))
